# Generated by Django 6.0.3 on 2026-03-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_brand_collection_dailyopsreport_product_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL de imagen del producto (Unsplash, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tier',
            field=models.CharField(choices=[('entry', 'Inicial'), ('mid', 'Intermedio'), ('pro', 'Pro')], default='entry', max_length=10),
        ),
    ]
